// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrxonfwdpvpmdciwxpnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyeG9uZndkcHZwbWRjaXd4cG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MjI1NjAsImV4cCI6MjA1NTk5ODU2MH0.V1r3Ez7luU5Vfsy22odIPDC734jD1r6Ic8Laxrgvhls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);